# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="pichot"

# Example aliases
alias zshconfig="subl ~/.zshrc"
alias ohmyzsh="subl ~/.oh-my-zsh"

# Comment this out to disable weekly auto-update checks
DISABLE_AUTO_UPDATE="false"

plugins=(git bundler rails)
source $ZSH/oh-my-zsh.sh

# Exports
export PATH=/Users/pichot/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/X11/bin
export EDITOR='subl -w'
export RUBY_GC_MALLOC_LIMIT=60000000
export RUBY_FREE_MIN=200000
export CFLAGS="-march=native -O2 -fomit-frame-pointer -pipe"

# Pythonbrew
[[ -s $HOME/.pythonbrew/etc/bashrc ]] && source $HOME/.pythonbrew/etc/bashrc

# LAMP
alias restart-apache="sudo apachectl restart"
alias restart-mysql="mysql.server restart"

# Postgres
alias start-postgres="pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start"
alias stop-postgres="pg_ctl -D /usr/local/var/postgres stop -s -m fast"

# Helper aliases
alias cppwd="pwd | pbcopy"
alias rake="noglob rake"

# Newline issues on prompt fix
unsetopt PROMPTCR